id = "herzha-theme"
name = "Herzha Theme"
version = "0.1.0"
schema_version = 1
authors = ["Madhanmaaz <madhanmaaz@gmail.com>"]
description = "Herzha theme for zed."
repository = "https://github.com/madhanmaaz/herzha-theme.git"
